[platformio]
default_envs = external_weather
src_dir = src
include_dir = include

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -DHABITAT_UART_BAUD=115200

[env:external_weather]
build_flags = ${env.build_flags} -DHABITAT_NODE=1

[env:external_radiation]
build_flags = ${env.build_flags} -DHABITAT_NODE=2

[env:internal_air]
build_flags = ${env.build_flags} -DHABITAT_NODE=3

[env:internal_imu]
build_flags = ${env.build_flags} -DHABITAT_NODE=4

[env:internal_co2]
build_flags = ${env.build_flags} -DHABITAT_NODE=5
